# pricebook configuration
pricebooks:
    # base id of pricebook
    id: "pricebook"

    # number of pricebooks to generate for this configuration
    elementCount: 5000

    # define range of prices per product and pricebook
    minAmountCount: 1
    maxAmountCount: 2

    # define range of price in USD
    minAmount: 1
    maxAmount: 1200

    # define pricebook custom attributes

    # randomly generate custom attributes for pricebook
    generatedAttributes:
      elementCount: 0

    # percentage of products to generate prices for (1.0 == 100%, 0.75 == 75%, etc.)
    coverage: 1.0

    # if true generate cheaper prices
    sales: false
